# ==========================================
# 1. MySQL DB ?? ??
# ==========================================
spring.datasource.url=jdbc:mysql://localhost:3306/onfit?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
# ? ?? 1234 ??? ??? ?? MySQL ????? ??? ?????!
spring.datasource.password=1234

# ==========================================
# 2. JPA ??
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ==========================================
# 3. MyBatis ??
# ==========================================
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=com.example.onfit.dto
mybatis.configuration.map-underscore-to-camel-case=true

openai.api-key=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
# ==========================================
# 4. Google OAuth2 (?? ???) ??
# ==========================================
spring.security.oauth2.client.registration.google.client-id=62774070396-n8u3876dk2l52r8mbjo86ppt27m37fvv.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email